"""create auction tables

Revision ID: 3bd7e5079fb1
Revises: 
Create Date: 2026-07-28 00:31:40.237642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bd7e5079fb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_name', sa.String(length=120), nullable=False),
    sa.Column('participants', sa.Integer(), nullable=False),
    sa.Column('starting_budget', sa.Integer(), nullable=False),
    sa.Column('minimum_bid', sa.Integer(), nullable=False),
    sa.Column('auction_mode', sa.String(length=30), nullable=False),
    sa.Column('roster_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('budget_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("auction_mode IN ('ROLE_BY_ROLE', 'FULL_RANDOM')", name='ck_auction_sessions_auction_mode_valid'),
    sa.CheckConstraint('minimum_bid > 0', name='ck_auction_sessions_minimum_bid_positive'),
    sa.CheckConstraint('participants >= 2', name='ck_auction_sessions_participants_min'),
    sa.CheckConstraint('starting_budget > 0', name='ck_auction_sessions_starting_budget_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auction_session_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_user_team', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auction_session_id'], ['auction_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auction_session_id', 'name', name='uq_teams_session_name')
    )
    op.create_index(op.f('ix_teams_auction_session_id'), 'teams', ['auction_session_id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auction_session_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=160), nullable=False),
    sa.Column('player_team', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=1), nullable=False),
    sa.Column('purchase_price', sa.Integer(), nullable=False),
    sa.Column('base_recommended_price_at_purchase', sa.Integer(), nullable=True),
    sa.Column('dynamic_recommended_price_at_purchase', sa.Integer(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('P', 'D', 'C', 'A')", name='ck_purchases_role_valid'),
    sa.CheckConstraint('purchase_price > 0', name='ck_purchases_price_positive'),
    sa.ForeignKeyConstraint(['auction_session_id'], ['auction_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auction_session_id', 'player_id', name='uq_purchases_session_player')
    )
    op.create_index(op.f('ix_purchases_auction_session_id'), 'purchases', ['auction_session_id'], unique=False)
    op.create_index(op.f('ix_purchases_team_id'), 'purchases', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_team_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_auction_session_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_teams_auction_session_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('auction_sessions')
    # ### end Alembic commands ###
